# 所有的icon都采用的Font Awesome资源，
# http://www.fontawesome.com.cn/faicons/
# 找到图标的名字后 使用方式为 icon: fas fa-图标名字

############################### DIY ###############################
baidu_analytics: true



############################### Basic Information ###############################
# 启用cdn加速，若有自定义CSS则false
# use_cdn: false

info:
  name: volantis
  version: ''
  docs: https://volantis.js.org/
  # cdn: # To use CDN, write 'use_cdn: true' in 'blog/_config.yml'.
    # css: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1.5/css/style.css
    # js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1.5/js/app.js


############################### Style ###############################
# 总体样式
style:
  # 页面的卡片宽度之和（文章列表+侧边卡片）
  max_width: 100% # Sum of body width and sidebar width
  # 顶部导航栏
  navbar:
    # 高度
    height: 30px
    # 效果。shadow：鼠标悬浮时有阴影，floatable：鼠标悬浮时浮动，blur：鼠标悬浮时模糊
    effect: [shadow, blur] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
    # 设置高亮
    highlight:
      language: true # show language of codeblock
      copy_btn: true
    # 文本的布局格式，居左，居右，自动，居中
    text_align: # left, right, justify, center
      h1: center
      h2: center
      h3: left
      h4: left
      p: justify
  # 设置间距
  gap:
    base: 10px
    h2: 48px # Spacing above H2 (only px unit)
    h3: 32px # Spacing above H3 (only px unit)
    h4: 16px # Spacing above H4 (only px unit)
    # 段落行间距
    line: .51rem # Paragraph spacing
    # 段落内部行间距
    inline: .5rem # Paragraph spacing within a block
  # 卡片的四角弧度
  border_radius:
    card: 5px
    codeblock: 5px
    searchbar: 5px
    button: 5px
  # 设置字体大小
  fontsize:
    root: 16px
    h1: 1.625rem
    h2: 1.375rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: 1rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
  # 设置字体
  fontfamily:
    bodyfont:
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    # codefont:
    #   name: 'Monaco'
    #   url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
    #   weight: normal
    #   style: normal
  # 设置颜色
  color:
    # site: '#E84D3B'
    # site_inner: '#FFCE48'
    # theme: '#E84D3B'
    site: 'gray'
    site_inner: 'black'
    theme: 'gray'
  #   site: '#21232F' # Website background color
  #   site_inner: '#FFCE48' # Text color inside the website background
  #   card: '#444' # Card background color
  #   text: '#fff' # The color of the text on the card.
  #   theme: '#ff9800' # Main color
  #   link: '#1BCDFC' # Link color
    hover: '#1BCDFC' # Link highlight color

  #   inner: '#333' # Text color inside the button
  #   block: '#555' # Block color
  #   inlinecode: yellow # Inline code color
  #   codeblock: '#555' # Codeblock color
  #   p: '#ccc' # Paragraph color




############################### Layout ###############################
# 封面图
cover:
  # 设置封面图样式
  scheme: blog # docs, blog
  # 设置是否展示封面图
  display:
    home: false
    archive: false
    others: false # can be written in front-matter 'cover: true'
  # 设置logo
  logo: 
  # 设置封面中的标题与副标题
  title: 
  subtitle: ''
  # 设置搜索框中的文本
  search: # search bar placeholder
  ## 设置导航
  # features:
  #   - name: 文档
  #     icon: fas fa-book
  #     url: https://volantis.js.org/getting-started/
  #   - name: 博文
  #     icon: fas fa-rss
  #     url: https://volantis.js.org/archives/
  #   - name: 示例
  #     icon: fas fa-play-circle
  #     url: https://volantis.js.org/examples/
  #   - name: 源码
  #     icon: fas fa-file-code
  #     url: https://github.com/xaoxuu/hexo-theme-volantis/
  #     rel: external nofollow noopener noreferrer
  #     target: _blank
  #   - name: 鸣谢
  #     icon: fas fa-handshake
  #     url: https://volantis.js.org/contributors/


# 顶部导航栏
navbar:
  # 设置logo
  logo:
    img: 
    icon: 
    title: lluuiq
  # 设置导航栏菜单 on_desktop为pc端，on_mobile为移动端
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    # This menu will be displayed on the laptop or desktop.
    on_desktop:
      - name: 首页
        icon: fas fa-home
        url: /
      - name: 分类
        icon: fas fa-folder-open
        url: categories/
      - name: 标签
        icon: fas fa-tags
        url: tags/
      - name: 归档
        icon: fas fa-archive
        url: archives/
      - name: 友人帐
        icon: fas fa-link
        url: friends/
      - name: 关于我
        icon: fas fa-info-circle
        url: about/
    # This menu will be displayed on the mobile.
    on_mobile:
      - name: 首页
        icon: fas fa-home
        url: /
      - name: 分类
        icon: fas fa-folder-open
        url: categories/
      - name: 标签
        icon: fas fa-tags
        url: tags/
      - name: 归档
        icon: fas fa-archive
        url: archives/
      - name: 友人帐
        icon: fas fa-link
        url: friends/
      - name: 关于我
        icon: fas fa-info-circle
        url: about/
  # 导航栏的搜索框显示文本
  search: 想找些什么？   # Search bar placeholder


# 设置布局
layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, category, date, wordcount, top]
    # 列表类页面的侧边栏 qrcode二维码
    sidebar: [blogger, category, tagcloud, qrcode]
    # read more button
    readmore: Read More <i class="fas fa-chevron-right"></i>
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, category, date,wordcount, top]
      footer: [updated, tags, btns, wordcount]
    # 文章页面的侧边栏
    sidebar: [blogger, category, tagcloud, toc]
  # 文章布局，参数继承自 on_page
  on_post:
    # 文章页脚，自动在每一篇文章末尾添加
    article_footer: [copyright, donate]
  # 其他的页面布局暂时等于 on_list


# meta library
# 设置文章信息
meta:
  # 文章标题
  # 默认使用md标题
  title: # 暂无配置
  # 默认文章作者（可在front-matter中覆盖）
  author:
    avatar: https://gitee.com/lluuiq/blog_img/raw/master/img/20200528013457.png
    name: lluuiq
    url: https://lluuiq.com
  # 文章创建日期
  date:
    icon: fas fa-edit
    title: '发布于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-save
    title: '更新于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章置顶
  top:
    icon: fas fa-angle-double-up
  # 文章浏览计数
  counter:
    icon: fas fa-eye
  # 文章字数和阅读时长
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-tags
  # 分享
  share:
    - id: qq
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
    - id: qzone
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qzone.png
    - id: weibo
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
    # - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
    #   img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/wechat.png
  # 链接
  btns:
    edit:
      icon: fas fa-edit
      title: 在GitHub上编辑此页
      color: '#888'
    repo: # 源码链接
      icon: fas fa-file-code
      title: 源码
      color: '#508EF2'
    bug: # BUG反馈链接
      icon: fas fa-bug
      title: BUG
      color: '#FE5F58'
    doubt: # 疑问链接
      icon: fas fa-question-circle
      title: 疑问
      color: '#FFBD2B'
    idea: # 建议链接
      icon: fas fa-lightbulb
      title: 建议
      color: '#3DC550'
    faq: # FAQ链接
      icon: fas fa-comments
      title: FAQ
      color: '#29B1C9'
    feedback: # 反馈链接
      icon: fas fa-comment-dots
      title: 反馈
      color: '#1BCDFC'

# widget library
# 设置卡片信息
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  # 设置博主信息卡片
  blogger:
    # 设置该卡片的css类
    class: blogger
    # 设置是否在PC端、移动端展示
    display: [desktop] # [desktop, mobile]
    avatar: https://gitee.com/lluuiq/blog_img/raw/master/img/20200528013457.png
    title: lluuiq
    subtitle: fly me to the star
    jinrishici: false # 随机诗句
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  # 设置目录卡片，目录卡片仅在文章页面生效
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 目录
    # 是否显示序数
    list_number: false
    # 最小显示多少个多级标题
    min_depth: 2
    # 最大显示多少个多级标题
    max_depth: 5
  # ---------------------------------------
  # category widget
  # 设置分类卡片
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /categories/
  # ---------------------------------------
  # tagcloud widget
  # 设置云标签卡片
  tagcloud:
    class: tagcloud
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: 热门标签
      url: /tags/
    min_font: 14
    max_font: 24
    color: true
    start_color: '#999'
    end_color: '#555'
  # ---------------------------------------
  # related posts widget
  # 设置相关文章卡片
  related_posts:
    class: related_posts # npm i -S hexo-related-popular-posts
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-bookmark
      title: 相关文章
    max_count: 5
  # ---------------------------------------
  # copyright widget (valid only in articles)
  # 设置copyright卡片，该卡片仅生效于文章页面
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true
    permalink: '本文永久链接是：'
    content:
      - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
      - permalink
  # ---------------------------------------
  # qrcode widget
  # donate:
  #   class: qrcode
  #   display: [desktop, mobile] # [desktop, mobile]
  #   height: 64px  # Automatic height if not set
  #   fancybox: true
  #   images:
  #     - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
  #     - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/


# 设置页脚
footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  # 页脚显示什么东西，播放器，社交信息，license，信息，copyright
  layout: [aplayer, copyright, beian]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:mail@lluuiq.com
    - icon: fab fa-github
      url: https://github.com/lluuiq
    - icon: fab fa-qq
      url: http://wpa.qq.com/msgrd?v=3&uin=844520941&site=qq&menu=yes
    # - icon: icon-CN_bilibili
    #   url: https://space.bilibili.com/5988692
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=118762977
  copyright: '[Copyright © lluuiq](https://lluuiq.com)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  beian: '[豫ICP备19027219号](http://beian.miit.gov.cn)<br>京公网备案 41140302000094号'


############################### SEO ###############################
# 优化SEO，不用修改
seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter


############################### Plugins ###############################
# 设置接口，根据需要修改
plugins:
  # Required plugins:
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.4/dist/jquery.min.js

  ######## Plugins to improve loading speed:
  # Preload (The menu's url must end with ‘/’)
  instant_page: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/instant_page.js

  ######## Plugins to optimize the experience:
  # Picture Zoom
  fancybox:
    css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # Page Scrolling Animation
  scrollreveal: #https://cdn.jsdelivr.net/npm/scrollreveal@4.0.5/dist/scrollreveal.min.js

  # Codeblock Copy Button
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  # mathjax
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  ######## Plugins for SEO:
  # Traffic statistics (very slow loading)
  busuanzi: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

  # npm i --save hexo-wordcount
  wordcount: true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # Typing Effects
  comment_typing: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  # 修改幻灯片背景的设置
  backstretch:
    # 是否显示幻灯片
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    # cover：仅仅在封面处展示，fixed：填充到整个页面
    position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    # 持续时间
    duration: 20000       # Duration (ms)
    # 淡入时间
    fade: 1500            # fade duration (ms) (Not more than 1500)
    # 图片
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      # - http://blogimg.wa2000.cn/blog/20200323/3E2JjtuuHclX.png?imageslim
      - https://cdn.jsdelivr.net/gh/lluuiq/blog_img/img/background.png
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  # 播放器设置
  aplayer:
    # 是否启用播放器
    enable: true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js
    # Required
    # 设置播放器款式 网易云，腾讯，酷狗，虾米，百度
    server: netease   # netease, tencent, kugou, xiami, baidu
    # 设置类型，song：单曲 playlist：歌单 album：专辑
    type: playlist    # song, playlist, album, search, artist
    # 根据设置的类型填入id
    id: 4945153572  # song id / playlist id / album id / search keyword
    # Optional
    # 是否固定到页面左下角
    fixed: true      # enable fixed mode
    # 主题颜色
    theme: '#1BCDFC'  # main color
    # 自动播放
    autoplay: false   # audio autoplay
    # 播放类型 list列表播放，random随机
    order: random       # player play order, values: 'list', 'random'
    # 循环方式
    loop: all         # player loop play, values: 'all', 'one', 'none'
    # 默认音量
    volume: 0.3       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    # 打开歌曲列表时的最大高度
    list_max_height: 500px # list max height
    list_folded: true




############################### Comments ###############################
# 设置评论
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  # 设置评论服务商
  service: valine # valine, disqus, gitalk, livere
  valine:
    appId: kKfWnugSqGAcPYpeH8wNYltU-gzGzoHsz # your appId
    appKey: NdwLtnM2yUza1v2VOJpKkQ4q # your appKey
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0/js/valine.js
    path: # All pages use the same path (share the same comments data)
    meta: nick,mail,link #valine comment header info
    placeholder: 有什么想说的吗？ # valine comment input placeholder(like: Please leave your footprints )
    avatar: mp # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    verify: true # valine verify code (true/false)
    notify: true # valine mail notify (true/false)
    lang: zh-cn
    highlight: true
    visitor: false # unavailable for now...
  disqus:
    shortname:
  # gitalk:
    # clientID: 0be79de503d8cfb1e930
    # clientSecret: f5758a63cce89f357e251159baec4c0066afeaea
    # repo: https://github.com/lluuiq/lluuiq.github.io
    # owner: lluuiq
    # admin: lluuiq
  # livere:
    # uid: MTAyMC80NTkzOC8yMjQ0OQ




############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i -S hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:
